#!/usr/bin/env bash

case "$1" in
    "--get")
        find-me-daddy --get | dmenu | xclip -in -selection clipboard
        ;;
    "--add")
        find-me-daddy --add
        ;;
    *) echo "Comand $1 is not avalible"
esac
